general {
    hide_cursor = false
}

auth {
    fingerprint {
        enabled = false
    }
}

background {
    monitor =
    color = rgb(090c10)
}

label {
    monitor =
    text = Session Stack recovery. Enter your password.
    color = rgb(ddd8c4)
    font_size = 18
    position = 0, 80
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 400, 60
    outline_thickness = 2
    outer_color = rgb(ef4650)
    inner_color = rgb(101419)
    font_color = rgb(ddd8c4)
    fade_on_empty = false
    position = 0, 0
    halign = center
    valign = center
}
