// Generated by scripts/generate-system-data.py; do not edit.
import QtQuick

QtObject {
    readonly property bool isDemo: true
    readonly property bool passwordAuthenticationEnabled: true
    readonly property bool faceAuthenticationEnabled: false
    readonly property bool fingerprintAuthenticationEnabled: false
    readonly property var users: [{"username":"operator","label":"OPERATOR","role":"LOCAL OPERATOR","faceAuthenticationEnabled":false,"fingerprintAuthenticationEnabled":false}]
    readonly property var systems: [{"id":"hyprland-uwsm","label":"HYPRLAND / UWSM","detail":"WAYLAND","command":["uwsm","start","-e","-D","Hyprland","hyprland.desktop"]},{"id":"hyprland","label":"HYPRLAND","detail":"WAYLAND","command":["/usr/bin/start-hyprland"]}]
}
